first_name = "xpath://input[@id= 'FirstName']"
last_name = "xpath://input[@id= 'LastName']"
email = "xpath://input[@id= 'Email']"
link_address = "xpath://div[@class = 'listbox']//a[text() = 'Addresses']"
link_order ="xpath://div[@class = 'listbox']//a[text() = 'Orders']"
