btn_add_new = "xpath://button[text() = 'Add new']"
Address_FirstName = "id:Address_FirstName"
Address_LastName = "id:Address_LastName"
Address_Email = "id:Address_Email"
Address_Company = "id:Address_Company"
Address_CountryId = "id:Address_CountryId"
Address_StateProvinceId = "id:Address_StateProvinceId"
Address_City = "id:Address_City"
Address_Address1 = "id:Address_Address1"
Address_ZipPostalCode = "id:Address_ZipPostalCode"
Address_PhoneNumber = "id:Address_PhoneNumber"
btn_save = "xpath://button[text() ='Save']"
lbl_wait = "id:states-loading-progress"


