sitemap = "xpath://a[text() = 'Sitemap']"
shipping_return = "xpath://a[text() = 'Shipping & returns']"
Privacy_notice = "xpath://a[text() = 'Privacy notice']"
Conditions_of_Use = "xpath://a[text() = 'Conditions of Use']"
about_us = "xpath://a[text() = 'About us']"
Contact_us = "xpath://a[text() = 'Contact us']"
search = "xpath://a[text() = 'Search']"
News = "xpath://a[text() = 'News']"
Blog = "xpath://a[text() = 'Blog']"
Recently_viewed_products = "xpath://a[text() = 'Recently viewed products']"
Compare_products_list = "xpath://a[text() = 'Compare products list']"
New_products = "xpath://a[text() = 'New products']"
my_account = "xpath://a[text() = 'My account']"
orders = "xpath://a[text() = 'Orders']"
Addresses = "xpath://a[text() = 'Addresses']"
Shopping_cart = "xpath: //a[text() = 'Shopping cart']"
Wishlist = "xpath://a[text() = 'Wishlist']"
Apply_for_vendor_account = "xpath://a[text() = 'Apply for vendor account']"
facebook = "xpath://a[text() = 'Facebook']"
Twitter = "xpath://a[text() = 'Twitter']"
RSS = "xpath://a[text() = 'RSS']"
YouTube = "xpath://a[text() = 'YouTube']"
newsletter_email ="id:newsletter-email"
subscribe ="id:newsletter-subscribe-button"
