old_password = "xpath://input[@id = 'OldPassword']"
new_password = "xpath://input[@id = 'NewPassword']"
confirm_new_password = "xpath://input[@id = 'ConfirmNewPassword']"
btn_change_password = "xpath://button[text() = 'Change password']"
bar_success = "xpath://div[@class = 'bar-notification success']"
link_change_password = "xpath://a[text() = 'Change password']"
div_error_mess = "xpath://div[contains(@class , 'error')]"
Confirm_not_match = "xpath://span[@id = 'ConfirmNewPassword-error' and contains(text(), 'do not match')]"
Confirm_require = "xpath://span[@id = 'ConfirmNewPassword-error' and contains(text(), 'require')]"
old_password_error = "xpath://span[@id='OldPassword-error']"
new_password_error = "xpath://span[@id='NewPassword-error']"
confirm_password_error = "xpath://span[@id='ConfirmNewPassword-error']"
least_6_char = "xpath://li[contains(text() , 'least 6')]"
error_match_old_password = "xpath://li[contains(text() , 'same as one of the last passwords you used')]"