
gender_name= "Gender"
first_name = "id:FirstName"
last_name = "id:LastName"
list_day = "xpath://select[@name='DateOfBirthDay']"
list_month = "xpath://select[@name='DateOfBirthMonth']"
list_year = "xpath://select[@name='DateOfBirthYear']"
email = "id:Email"
password = "id:Password"
company = "id:Company"
confirm_password = "id:ConfirmPassword"
register_button = "id:register-button"
first_name_error = "id:FirstName-error"
last_name_error = "LastName-error"
email_error = "Email-error"
password_error = "Password-error"
confirm_password_error = "ConfirmPassword-error"