computer_link = "xpath://div[@class='side-2']//a[text() ='Computers ']"
desktops_link = "xpath://div[@class='side-2']//a[text() ='Desktops ']"
notebook_link = "xpath://div[@class='side-2']//a[text() ='Notebooks ']"
Software_link = "xpath://div[@class='side-2']//a[text() ='Software ']"
Electronics_link = "xpath://div[@class='side-2']//a[text() ='Electronics ']"
camera_and_photo_link = "xpath://div[@class='side-2']//a[text() ='Camera & photo ']"
Cell_phones = "xpath://div[@class='side-2']//a[text() ='Cell phones ']"
Others = "xpath://div[@class='side-2']//a[text() ='Others ']"
Apparel = "xpath://div[@class='side-2']//a[text() ='Apparel ']"
shoes_link = "xpath://div[@class='side-2']//a[text() ='Shoes ']"
clothing_link = "xpath: //div[@class='side-2']//a[text() ='Clothing ']"
accessories_link = "xpath://div[@class='side-2']//a[text() ='Accessories ']"
Digital_downloads = "xpath://div[@class='side-2']//a[text() ='Digital downloads ']"
Books = "xpath://div[@class='side-2']//a[text() ='Books ']"
Jewelry = "xpath://div[@class='side-2']//a[text() ='Jewelry ']"
Gift_Cards = "xpath://div[@class='side-2']//a[text() ='Gift Cards ']"
Apple_Manufacturers = "xpath://div[@class='side-2']//a[text() ='Apple']"
Hp_Manufacturers = "xpath://div[@class='side-2']//a[text() ='HP']"
View_all_manufactures = "xpath://div[@class='side-2']//a[text() ='View all']"

cpu_intel_core_i5 = "xpath://label[text() = ' Intel Core i5 ']/parent::li/input"
cpu_intel_core_i7 = "xpath://label[text() = ' Intel Core i7 ']/parent::li/input"

memory_4g = "xpath://label[text() = ' 4 GB ']/parent::li/input"
memory_8g = "xpath://label[text() = ' 8 GB ']/parent::li/input"
memory_16g = "xpath://label[text() = ' 16 GB ']/parent::li/input"

color_grey = "xpath://label[text() = ' Grey ']/parent::li/input"
color_red = "xpath://label[text() = ' Red ']/parent::li/input"
color_blue = "xpath://label[text() = ' Blue ']/parent::li/input"